import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// This app is served as a sub-page of the AudioProto site at /charts/, gated by
// a token link. `base` makes the built asset URLs resolve under /charts/, and
// the output is written straight into the parent site's public/charts so it
// ships with the rest of the static site (and is regenerated by the optional
// Cloudflare Pages build command: `cd charts-app && npm ci && npm run build`).
export default defineConfig({
  plugins: [react()],
  base: "/charts/",
  build: {
    outDir: "../public/charts",
    emptyOutDir: true,
  },
});
